@startuml

skin rose
actor "SP Debitore" as SPD
participant "Activation Service" as AS
database "Database" as DB

SPD -> AS: DELETE /activations/{activationId}
activate AS

AS -> DB: findById
activate DB

alt Activation not found
    DB --> AS: empty
    AS --> SPD: 404 Not Found

else Activation found
    DB --> AS: Payer
    deactivate DB

    alt Access Denied
        AS -> AS: verifySubjectRequest throws AccessDeniedException
        note right: Subject in token doesn't match Service Provider ID in Payer entity

    else Access Granted
        AS -> AS: verifySubjectRequest is verified
        note right: Subject in token matches Service Provider ID in Payer entity

        AS -> DB: save deleted activation
        note right: Moves activation record to a separate collection
        activate DB

        DB --> AS: saved
        deactivate DB

        AS -> DB: deleteById
        activate DB

        DB -> AS: deleted
        deactivate DB

        AS --> SPD: 204 No Content
        deactivate AS
    end
end

@enduml
