@startuml

!theme materia

actor "Client" as Client
participant "SendAPIControllerImpl" as Controller
participant "SendRTPServiceImpl" as Service
participant "RtpRepository\n(Cosmos API Mongo)" as Repository
participant "Azure Data Explorer" as ADX
participant "RtpDtoMapper" as Mapper

Client -> Controller : GET /rtps/{rtpId}
activate Controller
note right of Controller : @PreAuthorize("hasRole('read_rtp_send')")

Controller -> Service : findRtp(rtpId)
activate Service

Service -> Repository : findById(ResourceID)

alt RTP found in Cosmos
    Repository --> Service : Mono<Rtp>

else RTP not found in Cosmos
    Repository --> Service : Mono.empty()
    Service -> ADX : findRtp(rtpId)

    alt RTP found in Azure Data Explorer
        ADX --> Service : Mono<Rtp>
    else RTP not found in Azure Data Explorer
        ADX --> Service : Mono.empty()
        Service --> Controller : error(RtpNotFoundException)
        deactivate Service
        Controller --> Client : 404 Not Found
        deactivate Controller
        return
    end
end

Service --> Controller : Mono<Rtp>
deactivate Service

Controller -> Mapper : toRtpDto(Rtp)
activate Mapper
Mapper --> Controller : RtpDto
deactivate Mapper

Controller --> Client : ResponseEntity<RtpDto>
deactivate Controller

@enduml