@startuml
skin rose
title RTP State Diagram

state CREATED
state SENT
state RFC_SENT 

state "Error statuses" as ES {
    state ERROR_SEND
    state ERROR_CANCEL
}

state "Accepted statuses" as AS {
    state ACCEPTED
    state USER_ACCEPTED
}

state "Rejected statuses" as RS {
    state REJECTED
    state USER_REJECTED
}

state "Cancelled statuses" as CS {
    state CANCELLED
    state CANCELLED_REJECTED
    state CANCELLED_PAID
    state CANCELLED_ACCR
}

[*] --> CREATED

CREATED --> SENT : SEND_RTP
CREATED --> ERROR_SEND : ERROR_SEND_RTP

SENT --> AS : ACCEPT_RTP
SENT --> RS : REJECT_RTP
SENT --> AS : USER_ACCEPT_RTP
SENT --> RS : USER_REJECT_RTP
SENT --> PAID : PAY_RTP
AS --> PAID : PAY_RTP

' Nuovo Flusso RFC
SENT --> RFC_SENT : CANCEL_RTP
AS --> RFC_SENT : CANCEL_RTP

' Gestione esiti da RFC_SENT
RFC_SENT --> CS : CALLBACK_RFC_SUCCESS
RFC_SENT --> ERROR_CANCEL : ERROR_CANCEL_RTP

' Sottostati di cancellazione
CANCELLED --> CANCELLED_ACCR : CANCEL_RTP_ACCR
CANCELLED --> CANCELLED_REJECTED : CANCEL_RTP_REJECTED
CANCELLED --> CANCELLED_PAID : CANCEL_RTP_PAID

PAID --> [*]
RS --> [*]
ES --> [*]
CS --> [*]

@enduml