@startuml
!theme materia

title RTP Send Flow

participant "RTP-CONSUMER" as CONSUMER
participant "MS-SENDER" as SENDER

autonumber

CONSUMER -> SENDER: POST /gpd/message
activate SENDER

SENDER -> SENDER: validate payload

SENDER -> SENDER: determine operation type\n(CREATE, UPDATE, DELETE)

alt CREATE
    SENDER -> SENDER: CREATE RTP
    note right of SENDER
      See diagram: RTP Create Flow
    end note

else UPDATE
    SENDER -> SENDER: UPDATE RTP
    note right of SENDER
      See diagram: RTP Update Flow
    end note

else DELETE
    SENDER -> SENDER: DELETE RTP
    note right of SENDER
      See diagram: RTP RFC Flow
    end note
end


deactivate SENDER

@enduml
