on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - image-gen
    paths:
      - 'diagrams/**/*.drawio'

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code repository
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Generate Drawio Images (C4)
        uses: severgroup-tt/actions-drawio-cli@757714b9f66bbdf0b3d05d3e5941016ad4b27861 # v1.0.0
        with:
          format: png
          source: diagrams/c4
          destination: diagrams/c4

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 #v9.1.4
        with:
          add: 'diagrams'
          message: 'Diagrams commit'
