name: Generate Drawio Images

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main" 
  push:
    branches:
      - image-gen
    paths:
      - 'diagrams/**/*.drawio'

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate Drawio Images (C4)
        uses: severgroup-tt/actions-drawio-cli@v1.0.0
        with:
          format: png
          source: diagrams/c4
          destination: diagrams/c4